sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t soramkirtep/docker-react -f Dockerfile .

script:
  - docker run -e CI=true soramkirtep/docker-react npm run test -- --coverage